import numpy as np
import scipy.interpolate as interp
import matplotlib.pyplot as plt

_NACA_EFF_15_DATA = np.loadtxt('experimental_data/naca_efficiency_15.csv', skiprows=1, delimiter=',')
_NACA_EFF_20_DATA = np.loadtxt('experimental_data/naca_efficiency_20.csv', skiprows=1, delimiter=',')
_NACA_EFF_25_DATA = np.loadtxt('experimental_data/naca_efficiency_25.csv', skiprows=1, delimiter=',')
_NACA_EFF_30_DATA = np.loadtxt('experimental_data/naca_efficiency_30.csv', skiprows=1, delimiter=',')
_NACA_EFF_35_DATA = np.loadtxt('experimental_data/naca_efficiency_35.csv', skiprows=1, delimiter=',')
_NACA_EFF_40_DATA = np.loadtxt('experimental_data/naca_efficiency_40.csv', skiprows=1, delimiter=',')
_NACA_EFF_45_DATA = np.loadtxt('experimental_data/naca_efficiency_45.csv', skiprows=1, delimiter=',')

_NACA_THRUST_15_DATA = np.loadtxt('experimental_data/naca_thrust_15.csv', skiprows=1, delimiter=',')
_NACA_THRUST_20_DATA = np.loadtxt('experimental_data/naca_thrust_20.csv', skiprows=1, delimiter=',')
_NACA_THRUST_25_DATA = np.loadtxt('experimental_data/naca_thrust_25.csv', skiprows=1, delimiter=',')
_NACA_THRUST_30_DATA = np.loadtxt('experimental_data/naca_thrust_30.csv', skiprows=1, delimiter=',')
_NACA_THRUST_35_DATA = np.loadtxt('experimental_data/naca_thrust_35.csv', skiprows=1, delimiter=',')
_NACA_THRUST_40_DATA = np.loadtxt('experimental_data/naca_thrust_40.csv', skiprows=1, delimiter=',')
_NACA_THRUST_45_DATA = np.loadtxt('experimental_data/naca_thrust_45.csv', skiprows=1, delimiter=',')

_NACA_POWER_15_DATA = np.loadtxt('experimental_data/naca_power_15.csv', skiprows=1, delimiter=',')
_NACA_POWER_20_DATA = np.loadtxt('experimental_data/naca_power_20.csv', skiprows=1, delimiter=',')
_NACA_POWER_25_DATA = np.loadtxt('experimental_data/naca_power_25.csv', skiprows=1, delimiter=',')
_NACA_POWER_30_DATA = np.loadtxt('experimental_data/naca_power_30.csv', skiprows=1, delimiter=',')
_NACA_POWER_35_DATA = np.loadtxt('experimental_data/naca_power_35.csv', skiprows=1, delimiter=',')
_NACA_POWER_40_DATA = np.loadtxt('experimental_data/naca_power_40.csv', skiprows=1, delimiter=',')
_NACA_POWER_45_DATA = np.loadtxt('experimental_data/naca_power_45.csv', skiprows=1, delimiter=',')

NACA_EFF_15_MAX = np.max(_NACA_EFF_15_DATA[:,0])
NACA_EFF_20_MAX = np.max(_NACA_EFF_20_DATA[:,0])
NACA_EFF_25_MAX = np.max(_NACA_EFF_25_DATA[:,0])
NACA_EFF_30_MAX = np.max(_NACA_EFF_30_DATA[:,0])
NACA_EFF_35_MAX = np.max(_NACA_EFF_35_DATA[:,0])
NACA_EFF_40_MAX = np.max(_NACA_EFF_40_DATA[:,0])
NACA_EFF_45_MAX = np.max(_NACA_EFF_45_DATA[:,0])

NACA_THRUST_15_MAX = np.max(_NACA_THRUST_15_DATA[:,0])
NACA_THRUST_20_MAX = np.max(_NACA_THRUST_20_DATA[:,0])
NACA_THRUST_25_MAX = np.max(_NACA_THRUST_25_DATA[:,0])
NACA_THRUST_30_MAX = np.max(_NACA_THRUST_30_DATA[:,0])
NACA_THRUST_35_MAX = np.max(_NACA_THRUST_35_DATA[:,0])
NACA_THRUST_40_MAX = np.max(_NACA_THRUST_40_DATA[:,0])
NACA_THRUST_45_MAX = np.max(_NACA_THRUST_45_DATA[:,0])

NACA_POWER_15_MAX = np.max(_NACA_POWER_15_DATA[:,0])
NACA_POWER_20_MAX = np.max(_NACA_POWER_20_DATA[:,0])
NACA_POWER_25_MAX = np.max(_NACA_POWER_25_DATA[:,0])
NACA_POWER_30_MAX = np.max(_NACA_POWER_30_DATA[:,0])
NACA_POWER_35_MAX = np.max(_NACA_POWER_35_DATA[:,0])
NACA_POWER_40_MAX = np.max(_NACA_POWER_40_DATA[:,0])
NACA_POWER_45_MAX = np.max(_NACA_POWER_45_DATA[:,0])

NACAEfficiency15 = interp.CubicSpline(_NACA_EFF_15_DATA[:,0], _NACA_EFF_15_DATA[:,1])
NACAEfficiency20 = interp.CubicSpline(_NACA_EFF_20_DATA[:,0], _NACA_EFF_20_DATA[:,1])
NACAEfficiency25 = interp.CubicSpline(_NACA_EFF_25_DATA[:,0], _NACA_EFF_25_DATA[:,1])
NACAEfficiency30 = interp.CubicSpline(_NACA_EFF_30_DATA[:,0], _NACA_EFF_30_DATA[:,1])
NACAEfficiency35 = interp.CubicSpline(_NACA_EFF_35_DATA[:,0], _NACA_EFF_35_DATA[:,1])
NACAEfficiency40 = interp.CubicSpline(_NACA_EFF_40_DATA[:,0], _NACA_EFF_40_DATA[:,1])
NACAEfficiency45 = interp.CubicSpline(_NACA_EFF_45_DATA[:,0], _NACA_EFF_45_DATA[:,1])

NACAThrust15 = interp.CubicSpline(_NACA_THRUST_15_DATA[:,0], _NACA_THRUST_15_DATA[:,1])
NACAThrust20 = interp.CubicSpline(_NACA_THRUST_20_DATA[:,0], _NACA_THRUST_20_DATA[:,1])
NACAThrust25 = interp.CubicSpline(_NACA_THRUST_25_DATA[:,0], _NACA_THRUST_25_DATA[:,1])
NACAThrust30 = interp.CubicSpline(_NACA_THRUST_30_DATA[:,0], _NACA_THRUST_30_DATA[:,1])
NACAThrust35 = interp.CubicSpline(_NACA_THRUST_35_DATA[:,0], _NACA_THRUST_35_DATA[:,1])
NACAThrust40 = interp.CubicSpline(_NACA_THRUST_40_DATA[:,0], _NACA_THRUST_40_DATA[:,1])
NACAThrust45 = interp.CubicSpline(_NACA_THRUST_45_DATA[:,0], _NACA_THRUST_45_DATA[:,1])

NACAPower15 = interp.CubicSpline(_NACA_POWER_15_DATA[:,0], _NACA_POWER_15_DATA[:,1])
NACAPower20 = interp.CubicSpline(_NACA_POWER_20_DATA[:,0], _NACA_POWER_20_DATA[:,1])
NACAPower25 = interp.CubicSpline(_NACA_POWER_25_DATA[:,0], _NACA_POWER_25_DATA[:,1])
NACAPower30 = interp.CubicSpline(_NACA_POWER_30_DATA[:,0], _NACA_POWER_30_DATA[:,1])
NACAPower35 = interp.CubicSpline(_NACA_POWER_35_DATA[:,0], _NACA_POWER_35_DATA[:,1])
NACAPower40 = interp.CubicSpline(_NACA_POWER_40_DATA[:,0], _NACA_POWER_40_DATA[:,1])
NACAPower45 = interp.CubicSpline(_NACA_POWER_45_DATA[:,0], _NACA_POWER_45_DATA[:,1])